-- Auto-generated by generate_voicelines.py. The data tables below
-- are generated; the logic under them is meant to be read and
-- adjusted by hand.
--
-- KNOWN LIMITATIONS:
--   1. Voice sync is per dialogue key (per show_text call), not per
--      on-screen page within one multi-page speech.
--   2. Voice plays via raw love.audio, not the engine's mod.content.sfx
--      registry, because the exact "trigger this registered sfx now"
--      call wasn't confirmed from the docs. Works today; revisit for
--      volume-slider integration.
--   3. Page-break codes (\011/\012) in the source translation were
--      converted to plain \n - unverified against how this engine
--      actually paginates multi-page dialogue. Watch for run-on or
--      oddly-broken text in longer speeches.
--   4. English voice lines table is empty until real English audio is
--      generated - see generate_voicelines.py --english-translations.

-- Danish dialogue text, keyed the same as DANISH_VOICE_LINES below.
-- \011/\012 (the old pret-disassembly page-break codes) were converted
-- to plain \n at generation time - see load_translations() in
-- generate_voicelines.py if you need to change that conversion.
-- Æ/Ø/Å render as real characters via the custom glyph page registered
-- above (see write_font_glyphs()/DANISH_GLYPHS_PNG_B64 in
-- generate_voicelines.py) - no longer transliterated to AE/OE/AA.
local TEXT_TRANSLATIONS = {
    ["TEXT_ROAMING_TASK_M_1"] = "{NAME}:\nJeg har trænet mit\nhold hele morgenen!",
    ["TEXT_ROAMING_TASK_M_2"] = "{NAME}:\nJeg har lige fanget en ny\nPOKéMON - sikke et held!",
    ["TEXT_ROAMING_TASK_M_3"] = "{NAME}:\nJeg er på vej til næste\nby for at teste mine\nevner.",
    ["TEXT_ROAMING_TASK_M_4"] = "{NAME}:\nJeg holder pause, så mine\nPOKéMON kan hvile.",
    ["TEXT_ROAMING_TASK_M_5"] = "{NAME}:\nJeg leder efter en stærk\nmodstander at kæmpe mod!",
    ["TEXT_ROAMING_TASK_F_1"] = "{NAME}:\nJeg har trænet mit\nhold hele morgenen!",
    ["TEXT_ROAMING_TASK_F_2"] = "{NAME}:\nJeg har lige fanget en ny\nPOKéMON - sikke et held!",
    ["TEXT_ROAMING_TASK_F_3"] = "{NAME}:\nJeg er på vej til næste\nby for at teste mine\nevner.",
    ["TEXT_ROAMING_TASK_F_4"] = "{NAME}:\nJeg holder pause, så mine\nPOKéMON kan hvile.",
    ["TEXT_ROAMING_TASK_F_5"] = "{NAME}:\nJeg leder efter en stærk\nmodstander at kæmpe mod!",
    ["TEXT_ROAMING_FACT_1"] = "{NAME}:\nVidste du det? Hver gemt fil\ngiver din POKéMON et unikt\nID-nummer.",
    ["TEXT_ROAMING_FACT_2"] = "{NAME}:\nSjov detalje: nogle POKéMON\nudvikler sig kun ved bytte,\nikke kun ved level op!",
    ["TEXT_ROAMING_FACT_3"] = "{NAME}:\nJeg har hørt, at DITTO kan\nforvandle sig til næsten\nenhver POKéMON, den ser!",
    ["TEXT_ROAMING_FACT_4"] = "{NAME}:\nMAGIKARP er måske svag,\nmen GYARADOS er bestemt\nikke!",
    ["TEXT_ROAMING_FACT_5"] = "{NAME}:\nDe siger, at nogle POKéMON\nkun dukker op på bestemte\ntidspunkter af dagen.",
}



local ENGINE_STRING_PATTERNS = {

}
local ENGINE_STRING_AFTER_KEYS = {

}
local SPECIES_NAME_TO_VOICE_KEY = {

}

local DANISH_VOICE_LINES = {
    ["TEXT_ROAMING_TASK_M_1"] = "voicelines/TEXT_ROAMING_TASK_M_1.mp3",
    ["TEXT_ROAMING_TASK_M_2"] = "voicelines/TEXT_ROAMING_TASK_M_2.mp3",
    ["TEXT_ROAMING_TASK_M_3"] = "voicelines/TEXT_ROAMING_TASK_M_3.mp3",
    ["TEXT_ROAMING_TASK_M_4"] = "voicelines/TEXT_ROAMING_TASK_M_4.mp3",
    ["TEXT_ROAMING_TASK_M_5"] = "voicelines/TEXT_ROAMING_TASK_M_5.mp3",
    ["TEXT_ROAMING_TASK_F_1"] = "voicelines/TEXT_ROAMING_TASK_F_1.mp3",
    ["TEXT_ROAMING_TASK_F_2"] = "voicelines/TEXT_ROAMING_TASK_F_2.mp3",
    ["TEXT_ROAMING_TASK_F_3"] = "voicelines/TEXT_ROAMING_TASK_F_3.mp3",
    ["TEXT_ROAMING_TASK_F_4"] = "voicelines/TEXT_ROAMING_TASK_F_4.mp3",
    ["TEXT_ROAMING_TASK_F_5"] = "voicelines/TEXT_ROAMING_TASK_F_5.mp3",
    ["TEXT_ROAMING_FACT_M_1"] = "voicelines/TEXT_ROAMING_FACT_M_1.mp3",
    ["TEXT_ROAMING_FACT_M_2"] = "voicelines/TEXT_ROAMING_FACT_M_2.mp3",
    ["TEXT_ROAMING_FACT_M_3"] = "voicelines/TEXT_ROAMING_FACT_M_3.mp3",
    ["TEXT_ROAMING_FACT_M_4"] = "voicelines/TEXT_ROAMING_FACT_M_4.mp3",
    ["TEXT_ROAMING_FACT_M_5"] = "voicelines/TEXT_ROAMING_FACT_M_5.mp3",
    ["TEXT_ROAMING_FACT_F_1"] = "voicelines/TEXT_ROAMING_FACT_F_1.mp3",
    ["TEXT_ROAMING_FACT_F_2"] = "voicelines/TEXT_ROAMING_FACT_F_2.mp3",
    ["TEXT_ROAMING_FACT_F_3"] = "voicelines/TEXT_ROAMING_FACT_F_3.mp3",
    ["TEXT_ROAMING_FACT_F_4"] = "voicelines/TEXT_ROAMING_FACT_F_4.mp3",
    ["TEXT_ROAMING_FACT_F_5"] = "voicelines/TEXT_ROAMING_FACT_F_5.mp3",
}

local ENGLISH_VOICE_LINES = {
    -- (empty - no English audio generated yet)
}

-- Maps a fingerprint (see key_to_fingerprint() in generate_voicelines.py)
-- back to the real pret-style key, so static NPCs whose dialogue is
-- defined directly as target.def.text (bypassing script.command/
-- show_text entirely) can still have their voice line resolved.
local TEXT_ID_TO_KEY = {
    ["TEXT_ROAMING_TASK_M_1"] = "TEXT_ROAMING_TASK_M_1",
    ["TEXT_ROAMING_TASK_M_2"] = "TEXT_ROAMING_TASK_M_2",
    ["TEXT_ROAMING_TASK_M_3"] = "TEXT_ROAMING_TASK_M_3",
    ["TEXT_ROAMING_TASK_M_4"] = "TEXT_ROAMING_TASK_M_4",
    ["TEXT_ROAMING_TASK_M_5"] = "TEXT_ROAMING_TASK_M_5",
    ["TEXT_ROAMING_TASK_F_1"] = "TEXT_ROAMING_TASK_F_1",
    ["TEXT_ROAMING_TASK_F_2"] = "TEXT_ROAMING_TASK_F_2",
    ["TEXT_ROAMING_TASK_F_3"] = "TEXT_ROAMING_TASK_F_3",
    ["TEXT_ROAMING_TASK_F_4"] = "TEXT_ROAMING_TASK_F_4",
    ["TEXT_ROAMING_TASK_F_5"] = "TEXT_ROAMING_TASK_F_5",
    ["TEXT_ROAMING_FACT_1"] = "TEXT_ROAMING_FACT_1",
    ["TEXT_ROAMING_FACT_2"] = "TEXT_ROAMING_FACT_2",
    ["TEXT_ROAMING_FACT_3"] = "TEXT_ROAMING_FACT_3",
    ["TEXT_ROAMING_FACT_4"] = "TEXT_ROAMING_FACT_4",
    ["TEXT_ROAMING_FACT_5"] = "TEXT_ROAMING_FACT_5",
}

return function(mod)
    -- Persisted language choice ("danish" or "english"). Defaults to
    -- danish (matches this mod's original behavior before English
    -- support existed).
    local currentLanguage = mod.save:get("language")
    if currentLanguage == nil then
        currentLanguage = "danish"
    end
    local optionsRowsDumped = false

    -- Custom font glyphs for Danish characters not in the vanilla font
    -- (Æ Ø Å æ ø å). Registered as a new glyph page above the
    -- vanilla $60/$80 font ranges, with an embedded charmap binding each
    -- character to its glyph. Confirmed directly from real engine source
    -- (src/mods/Schemas.lua's own R.font schema and worked example -
    -- "seq"/"code" are the real field names, not "text"/"code" as an
    -- earlier, unverified version of this guessed) - a font page can
    -- carry its own charmap list directly as a convenience, rather than
    -- needing separate "charmap:<name>" registration calls per glyph.
    local DANISH_GLYPH_BASE = 0x180
    mod.content.font:register("danish_glyphs", {
        image = mod.assets:path("fonts/danish_glyphs.png"),
        base = DANISH_GLYPH_BASE,
        glyphsPerRow = 6,
        charmap = {
            { seq = "Æ", code = DANISH_GLYPH_BASE + 0 },
            { seq = "Ø", code = DANISH_GLYPH_BASE + 1 },
            { seq = "Å", code = DANISH_GLYPH_BASE + 2 },
            { seq = "æ", code = DANISH_GLYPH_BASE + 3 },
            { seq = "ø", code = DANISH_GLYPH_BASE + 4 },
            { seq = "å", code = DANISH_GLYPH_BASE + 5 },
        },
    })

    -- Text overrides are only applied for Danish - English needs none,
    -- since skipping the override entirely shows vanilla (guaranteed-
    -- accurate, extracted from your own ROM) English text. This check
    -- happens once at mod load, so a language change via the Options
    -- row below only affects TEXT after a restart - voice switches
    -- immediately since that's a live table lookup, not a one-time
    -- registration.
    --
    -- Wrapped in pcall, same reasoning as the SFX registration loop
    -- below: ~2582 override() calls running completely unprotected
    -- meant a single failure anywhere in that loop (bad schema,
    -- anything) would throw uncaught and halt this whole function
    -- right here - silently skipping EVERYTHING after it, including
    -- the very first writeDebugLog("=== mod loaded ===") call further
    -- down. That's indistinguishable from "the mod never loaded at
    -- all" from the outside, which is exactly the bug this fixes.
    if currentLanguage == "danish" then
        local textOverrideOk, textOverrideErr = pcall(function()
            for key, text in pairs(TEXT_TRANSLATIONS) do
                mod.content.text:override(key, text)
            end
        end)
        if not textOverrideOk then
            mod.log:info("Text override loop failed partway through: %s", tostring(textOverrideErr))
        end
    end

    -- Registers every voice line as an SFX def, so playback can go
    -- through the engine's own sanctioned audio path (src/core/Sound.lua's
    -- Sound.play) instead of only raw love.audio - confirmed real from
    -- direct engine source inspection, not a guess. Registering costs
    -- nothing at load time either way (Sound.lua caches lazily, only
    -- actually loading a Source on first play), so this happens
    -- unconditionally even if the Sound.play path below never ends up
    -- usable.
    --
    -- Wrapped in pcall: without this, a single failed register() call
    -- (wrong schema, anything) would throw uncaught and halt this whole
    -- function right here - meaning every hook/event registered further
    -- down (script.command, world.interacted, the Options rows, all of
    -- it) would silently never run at all. That's a total-silence bug
    -- far worse than just losing the Sound.play path, which is why this
    -- needed protecting even though playVoiceForKey already falls back
    -- gracefully on its own end.
    local sfxRegisterOk, sfxRegisterErr = pcall(function()
        for key, relPath in pairs(DANISH_VOICE_LINES) do
            mod.content.sfx:register("danish:" .. key, { file = mod.assets:path(relPath) })
        end
        for key, relPath in pairs(ENGLISH_VOICE_LINES) do
            mod.content.sfx:register("english:" .. key, { file = mod.assets:path(relPath) })
        end
    end)
    if not sfxRegisterOk then
        mod.log:info("SFX registration failed, falling back to love.audio only: %s", tostring(sfxRegisterErr))
    end

    -- require("src.core.Sound") matches the "supported require" pattern
    -- shown elsewhere in this engine's own docs (e.g. src.pokemon.Stats),
    -- but isn't itself confirmed to be on that allowlist - pcall so a
    -- failure here just means the fallback path below is used for
    -- everything, not a broken mod.
    local SoundModule = nil
    local soundOk = pcall(function()
        SoundModule = require("src.core.Sound")
    end)
    if not soundOk then
        SoundModule = nil
    end

    -- Sound.play(data, name) needs game.data - script.command's ctx has
    -- ctx.game directly (confirmed from src/script/ScriptRunner.lua's
    -- makeContext), so this is captured there and reused everywhere else
    -- that needs it (world.interacted's payload doesn't include game).
    -- Registries freeze after boot, so this reference stays valid for
    -- the whole session once set - caching it isn't just an optimization,
    -- it's the only way other trigger points can reach it at all.
    local cachedGameData = nil

    local currentSource = nil
    local currentKey = nil
    local sourceCache = {}

    -- Persisted on/off setting for voice playback. Defaults to on the
    -- first time this mod ever loads for a save; mod.save:get returns
    -- nil until something has been mod.save:set, so nil means
    -- "never touched this setting yet" here, not "off".
    local voiceEnabled = mod.save:get("voice_enabled")
    if voiceEnabled == nil then
        voiceEnabled = true
    end

    -- Separate on/off toggle specifically for battle text voice, since
    -- it's far more frequent than overworld dialogue (a new line for
    -- nearly every turn) and some players may want it off even with
    -- general voice on. Checked only in BattleState.startMessage's
    -- hook, below - overworld/menu voice is entirely unaffected by
    -- this setting.
    local battleVoiceEnabled = mod.save:get("battle_voice_enabled")
    if battleVoiceEnabled == nil then
        battleVoiceEnabled = true
    end

    -- Persisted volume as a simple 1-5 level (not raw percentage), each
    -- level mapped to a percentage in VOLUME_LEVELS. Level 1 = 100%,
    -- matching the volume control's previous default before this was
    -- simplified from an 11-step 0-100% cycle down to 5 steps.
    local VOLUME_LEVELS = {100, 75, 50, 25, 0}
    local voiceVolumeLevel = mod.save:get("voice_volume_level")
    if voiceVolumeLevel == nil then
        voiceVolumeLevel = 1
    end

    local function currentVolumePercent()
        return VOLUME_LEVELS[voiceVolumeLevel] or 100
    end

    local function applyVolume()
        if currentSource then
            currentSource:setVolume(currentVolumePercent() / 100)
        end
    end

    -- Speeds up voice playback when GAME SPEED is above normal.
    --
    -- CONFIRMED from the official hooks reference (not a guess): core.logic_speed
    -- fires once per frame, and next(game) resolves the actual GAME SPEED
    -- multiplier (1, 2, 3, 4, 10, 20, 30, 50, 75, 100, or 200 - GameSpeed.LEVELS).
    -- This wraps it purely as an observer (returns next(game) unchanged) and
    -- caches the current value for use elsewhere.
    --
    -- Worth knowing before relying on this: the engine's own GameSpeed.lua
    -- states audio deliberately does NOT scale with GAME SPEED ("so music
    -- and sfx play at normal pitch and tempo at every speed") - this
    -- feature intentionally goes against that convention. Capped well
    -- below the real multiplier (GAME SPEED can hit 200x) since a raw
    -- 200x pitch shift would just be noise, not "faster speech" - MAX_PITCH
    -- below is a judgment call, not something confirmed correct.
    local currentGameSpeed = 1
    local regOkLogicSpeed, regErrLogicSpeed = pcall(mod.hooks.wrap, mod.hooks, "core.logic_speed", function(next, game)
        local speed = next(game)
        currentGameSpeed = speed or 1
        return speed
    end)
    if not regOkLogicSpeed then
        mod.log:info("core.logic_speed registration failed: %s", tostring(regErrLogicSpeed))
    end

    local fastVoiceEnabled = mod.save:get("fast_voice_enabled")
    if fastVoiceEnabled == nil then
        fastVoiceEnabled = false
    end

    local MAX_VOICE_PITCH = 3

    local function getGameSpeedMultiplier()
        local mult = currentGameSpeed or 1
        if mult > MAX_VOICE_PITCH then
            mult = MAX_VOICE_PITCH
        end
        if mult < 1 then
            mult = 1
        end
        return mult
    end

    local function applyPlaybackSpeed()
        if currentSource then
            local mult = fastVoiceEnabled and getGameSpeedMultiplier() or 1
            currentSource:setPitch(mult)
        end
    end

    -- writeDebugLog is defined here, before playVoiceForKey/stopVoice,
    -- deliberately - Lua locals are only visible to code that comes
    -- AFTER their declaration in the source. It used to sit much later
    -- in this file (right where it's first called, "=== mod loaded
    -- ==="), which meant every reference to it from inside
    -- playVoiceForKey compiled as an undeclared GLOBAL lookup instead
    -- of the local upvalue - nil at runtime, since nothing sets a
    -- global by this name. That crashed playVoiceForKey on its own
    -- first line, every single time, silently (caught by the engine's
    -- hook error isolation, so nothing after it in the script.command
    -- handler ever ran either) - this was confirmed directly from a
    -- real debug log's own error output: "attempt to call global
    -- 'writeDebugLog' (a nil value)". This was very likely the actual
    -- root cause of the entire "no voice audio at all" investigation
    -- across many previous versions, not a Sound.play issue or
    -- anything else that got ruled out along the way - just a plain
    -- ordering bug in a helper function's declaration, unrelated to
    -- how audio itself gets played (love.audio.newSource/:play below
    -- are untouched by this fix).
    --
    --   Windows: %APPDATA%\love\pokemon-love2d\danish_voice_debug.log
    --   macOS:   ~/Library/Application Support/LOVE/pokemon-love2d/danish_voice_debug.log
    -- Delete that file before testing so you're only looking at fresh
    -- entries, then talk to an NPC and check what got written.
    local function writeDebugLog(line)
        local ok, err = pcall(function()
            love.filesystem.append("danish_voice_debug.log", line .. "\n")
        end)
        if not ok then
            mod.log:info("debug log write failed: %s", tostring(err))
        end
    end

    local function stopVoice()
        if currentSource then
            currentSource:stop()
        end
        currentSource = nil
        currentKey = nil
    end

    local function playVoiceForKey(key)
        writeDebugLog("playVoiceForKey ENTERED with key=" .. tostring(key))
        if not voiceEnabled then
            writeDebugLog("playVoiceForKey key=" .. key .. " ABORTED: voiceEnabled is false")
            return
        end

        local voiceTable = (currentLanguage == "english") and ENGLISH_VOICE_LINES or DANISH_VOICE_LINES
        local cacheKey = currentLanguage .. ":" .. key

        -- Only skip restarting if the same line is STILL actively
        -- playing - checking key equality alone isn't enough, since
        -- some NPCs (static ones resolved via world.interacted, not
        -- script.command) never fire script.ended to reset currentKey.
        -- Without the isPlaying() check, a finished clip would
        -- permanently block that same NPC from ever voicing again for
        -- the rest of the session.
        if cacheKey == currentKey and currentSource then
            local ok, playing = pcall(function() return currentSource:isPlaying() end)
            if ok and playing then
                return
            end
        end
        stopVoice()

        local relPath = voiceTable[key]
        if not relPath then
            writeDebugLog("playVoiceForKey key=" .. key .. " ABORTED: relPath is nil (voiceTable lookup found nothing, despite the outer voiceLineFound check saying it should)")
            return  -- no voice line for this key/language yet - fine, plays silently
        end

        local source = nil

        -- The Sound.play()/SFX-registry path (the "proper", sanctioned
        -- API) is intentionally NOT attempted here anymore. Confirmed
        -- via direct testing: pairing the pre-Google-integration Lua
        -- (which never touches Sound.play at all) with the exact same
        -- Google-generated audio files worked perfectly - proving the
        -- files were never the problem, and narrowing the actual fault
        -- specifically to this code path. Rather than keep chasing why
        -- Sound.play fails, this just goes straight to the fallback
        -- that's now confirmed reliable, exactly like the pre-Google
        -- version did. SoundModule/cachedGameData are left in place
        -- above (harmless, unused) rather than torn out, to keep this
        -- change minimal and easy to revert if Sound.play's issue ever
        -- gets root-caused and fixed properly.

        -- Fallback: raw love.audio - now the ONLY path, not a fallback
        -- in name only. Used whenever the Sound.play path isn't
        -- available (require failed, or game.data hasn't been captured
        -- yet - e.g. very early in a session before any script.command
        -- has fired).
        if not source then
            source = sourceCache[cacheKey]
            if not source then
                local fullPath = mod.assets:path(relPath)
                local ok, srcOrErr = pcall(love.audio.newSource, fullPath, "static")
                if not ok then
                    writeDebugLog("playVoiceForKey love.audio fallback FAILED for " .. cacheKey .. " (" .. fullPath .. "): " .. tostring(srcOrErr))
                    return
                end
                source = srcOrErr
                sourceCache[cacheKey] = source
                writeDebugLog("playVoiceForKey love.audio fallback loaded fresh source for " .. cacheKey)
            else
                writeDebugLog("playVoiceForKey love.audio fallback reused cached source for " .. cacheKey)
            end
            source:stop()
            source:play()
        end

        source:setVolume(currentVolumePercent() / 100)
        if fastVoiceEnabled then
            source:setPitch(getGameSpeedMultiplier())
        else
            source:setPitch(1)
        end
        currentSource = source
        currentKey = cacheKey

        -- The most direct possible check: ask the audio engine itself,
        -- right now, whether it believes this source is actually
        -- playing, and at what volume. If Sound.play() or the fallback
        -- "succeeded" (no error thrown) but the source isn't actually
        -- in a playing state, or volume is 0, THAT is the failure -
        -- distinct from every failure mode logged above, which all
        -- assumed success meant success.
        local checkOk, isPlayingNow = pcall(function() return source:isPlaying() end)
        local volOk, currentVol = pcall(function() return source:getVolume() end)
        writeDebugLog("playVoiceForKey FINAL STATE for " .. cacheKey .. ": isPlaying=" .. tostring(checkOk and isPlayingNow) .. " volume=" .. tostring(volOk and currentVol) .. " voiceEnabled=" .. tostring(voiceEnabled))
    end

    -- Sequenced voice playback: plays several clips back-to-back (a
    -- Pokemon's name, then the rest of a battle message), so lines like
    -- "PIKACHU wants to fight!" can say the real name instead of a
    -- generic placeholder. Deliberately kept entirely separate from
    -- playVoiceForKey/stopVoice/currentSource above - its own state
    -- (sequenceQueue/sequenceSource/sequenceIndex), its own love.audio
    -- sources - so this new mechanism cannot interfere with, or be
    -- interfered with by, the single-clip path everything else in this
    -- mod already uses successfully. Nothing above this point is
    -- touched or changed.
    local sequenceQueue = {}
    local sequenceSource = nil
    local sequenceIndex = 0

    local function playNextInSequence()
        sequenceIndex = sequenceIndex + 1
        local key = sequenceQueue[sequenceIndex]
        if not key then
            sequenceSource = nil
            return
        end
        local voiceTable = (currentLanguage == "english") and ENGLISH_VOICE_LINES or DANISH_VOICE_LINES
        local relPath = voiceTable[key]
        if not relPath then
            writeDebugLog("playNextInSequence: no voice line for key=" .. tostring(key) .. ", skipping to next")
            playNextInSequence()
            return
        end
        local fullPath = mod.assets:path(relPath)
        local ok, srcOrErr = pcall(love.audio.newSource, fullPath, "static")
        if not ok then
            writeDebugLog("playNextInSequence: love.audio.newSource FAILED for " .. tostring(key) .. " (" .. fullPath .. "): " .. tostring(srcOrErr))
            playNextInSequence()
            return
        end
        sequenceSource = srcOrErr
        sequenceSource:setVolume(currentVolumePercent() / 100)
        sequenceSource:play()
    end

    -- keys: an ordered list, e.g. ('SPECIESNAME_PIKACHU', 'ENGSTR_AFTER_...')
    local function playVoiceSequence(keys)
        if not voiceEnabled then return end
        if sequenceSource then
            sequenceSource:stop()
        end
        sequenceQueue = keys
        sequenceIndex = 0
        playNextInSequence()
    end

    -- Monkey-patches LOVE2D's own per-frame callback (confirmed real
    -- from direct engine source: the top-level main.lua's own "function
    -- love.update(dt)") to poll whether the current sequenced clip has
    -- finished and advance to the next one - love.audio sources have no
    -- built-in "finished" callback, only isPlaying() to poll. Nothing
    -- else in this mod needed a per-frame hook before this feature -
    -- playVoiceForKey plays one clip and stops there. Kept as narrow as
    -- possible: only ever touches the three sequence* locals above,
    -- never playVoiceForKey's own currentSource/currentKey, and always
    -- calls the real, original love.update right after regardless of
    -- what happens here, so a failure in this specific patch can't stop
    -- the game's own update loop from running at all.
    local updatePatchOk, updatePatchErr = pcall(function()
        local originalLoveUpdate = love.update
        if type(originalLoveUpdate) == "function" then
            love.update = function(dt)
                if sequenceSource and not sequenceSource:isPlaying() then
                    playNextInSequence()
                end
                return originalLoveUpdate(dt)
            end
        end
    end)
    if not updatePatchOk then
        writeDebugLog("love.update patch for sequenced voice failed: " .. tostring(updatePatchErr))
    end

    -- Diagnostic logging: writes every show_text call to a plain text
    -- file directly, using LÖVE2D's own filesystem API (the same one
    -- this mod already relies on for playing audio) rather than
    -- mod.log, since mod.log's actual display destination couldn't be
    -- found in the Mods menu. This writes to the game's normal save
    -- directory - same place your saves and mods folder live.
    -- (writeDebugLog itself is defined earlier now, right before
    -- stopVoice - see the comment there for why.)
    writeDebugLog("=== mod loaded ===")

    writeDebugLog("voiceEnabled at load = " .. tostring(voiceEnabled) .. " (saved value was " .. tostring(mod.save:get("voice_enabled")) .. ")")

    -- Universal fallback: catches voice triggers for scenes that never
    -- go through script.command, world.interacted, or intro.oak_speech
    -- at all - confirmed real via direct engine source (OverworldController.
    -- lua): some scenes (e.g. Oak stopping the player in Pallet Town's
    -- tall grass) are pushed by a VANILLA, built-in mapScripts.onStep
    -- hook, entirely separate from any hook this mod (or literal_handlers.
    -- lua) registers - so no amount of instrumenting our own trigger
    -- points would ever catch it. TextBox.new(game, text, ...) is the one
    -- constructor every text display in the whole game funnels through
    -- regardless of what triggered it, so wrapping it here - matching
    -- displayed text back to a voice-line key via a reverse lookup built
    -- once from TEXT_TRANSLATIONS (already embedded, no duplicate data) -
    -- catches this scene and any other similar vanilla-triggered case we
    -- haven't even found yet, in one place, instead of chasing each one
    -- individually. Safe to coexist with the explicit triggers already in
    -- place: playVoiceForKey's own replay guard means a key already
    -- playing just gets left alone, not restarted, so this can't
    -- double-trigger anything.
    if currentLanguage == "danish" then
        local textMatchOk, textMatchErr = pcall(function()
            local reverseLookup = {}
            for key, text in pairs(TEXT_TRANSLATIONS) do
                -- Skip empty translations entirely - an empty string
                -- means "not translated yet, show vanilla English" and
                -- should never be treated as a match target. Confirmed
                -- as a real, serious bug via an actual debug log:
                -- string.find(anyText, "", 1, true) trivially succeeds
                -- at position 1 for ANY text, so once an empty-valued
                -- key like _GreatlyFellText got into this table, the
                -- earliest-position substring search picked it over
                -- every genuine match, every single time - explaining
                -- why battle text (and the Cable Club welcome) never
                -- got real voice: they were all silently hijacked by
                -- this one empty entry before any real candidate was
                -- even considered.
                if text ~= "" and (not reverseLookup[text]) then
                    reverseLookup[text] = key
                end
            end

            -- Shared by every text-display hook below (TextBox.new,
            -- BattleState:startMessage, and anything else found later) -
            -- tries an exact match first (TEXT_TRANSLATIONS' dialogue,
            -- cheap table lookup), then falls back to a pattern search
            -- through ENGINE_STRING_PATTERNS (engine_strings' narrative
            -- battle/menu messages, which are either dynamically
            -- formatted with a real name at runtime, or - confirmed
            -- directly from real engine source, OverworldController.
            -- lua's nurseHeal - sometimes concatenated onto OTHER text
            -- before display, e.g. the Pokemon Center's welcome message
            -- plus its heal question joined with one "\f" between them.
            -- ENGINE_STRING_PATTERNS entries have no ^/$ anchors for
            -- exactly that reason - see build_lua_pattern()'s own
            -- docstring in generate_voicelines.py.
            local function findVoiceSequenceForText(text)
                if type(text) ~= "string" then return nil end
                -- Finds EVERY non-overlapping match in the displayed
                -- text - not just the single best one - since real
                -- engine source confirms multiple separate lines
                -- routinely get concatenated together before display
                -- (e.g. the Cable Club's welcome + "making preparations",
                -- or the Nurse's "fighting fit" + farewell). Voicing
                -- only the first of these left the rest of the message
                -- silent even though real, matching audio existed for
                -- it - confirmed directly from user reports after the
                -- earlier single-match version shipped. Every match
                -- (exact dialogue text, substring dialogue text, and
                -- engine_strings patterns) is collected with its
                -- position, sorted, and non-overlapping ones are kept
                -- in order, so the final sequence plays in the same
                -- order the text is actually read on screen.
                local candidates = {}

                local exactKey = reverseLookup[text]
                if exactKey then
                    table.insert(candidates, { pos = 1, endPos = #text, keys = { exactKey } })
                else
                    for translatedText, key in pairs(reverseLookup) do
                        local findOk, foundAt, foundEnd = pcall(string.find, text, translatedText, 1, true)
                        if findOk and foundAt then
                            table.insert(candidates, { pos = foundAt, endPos = foundEnd, keys = { key } })
                        end
                    end
                end

                for patternKey, luaPattern in pairs(ENGINE_STRING_PATTERNS) do
                    local matchOk, startPos, endPos, capture = pcall(string.find, text, luaPattern)
                    if matchOk and startPos then
                        local afterKey = ENGINE_STRING_AFTER_KEYS[patternKey]
                        local speciesKey = afterKey and capture and SPECIES_NAME_TO_VOICE_KEY[capture]
                        local keys
                        if afterKey and speciesKey then
                            keys = { speciesKey, afterKey }
                        else
                            keys = { patternKey }
                        end
                        table.insert(candidates, { pos = startPos, endPos = endPos, keys = keys })
                    end
                end

                if #candidates == 0 then
                    writeDebugLog("findVoiceSequenceForText: NO MATCH (exact, substring, or pattern) for text=" .. text:sub(1, 80))
                    return nil
                end

                table.sort(candidates, function(a, b) return a.pos < b.pos end)

                local sequence = {}
                local lastEnd = 0
                for _, candidate in ipairs(candidates) do
                    if candidate.pos > lastEnd then
                        for _, k in ipairs(candidate.keys) do
                            table.insert(sequence, k)
                        end
                        lastEnd = candidate.endPos
                    end
                end
                return sequence
            end

            -- Battle-text path (BattleState.startMessage below): no
            -- concept of "the player pressed A to turn the page" is
            -- available there, so this plays the whole found sequence
            -- back-to-back by clip duration - the same approach used
            -- everywhere before this fix. Kept as a separate, named
            -- function (rather than inlined) so both call sites stay
            -- readable.
            --
            -- Skips triggering a new clip entirely if one is already
            -- mid-playback, rather than interrupting it - confirmed via
            -- user report that battle messages were audibly cut off
            -- partway through. Battle messages can arrive faster than a
            -- clip's natural duration (the player pressing A quickly
            -- through several turns), and playVoiceSequence always
            -- stops whatever's currently playing before starting the
            -- next one - so without this check, a fast player would
            -- never hear a single complete line. Some messages ending
            -- up silent when battle moves quickly is a better trade-off
            -- than every line being chopped short.
            local function tryPlayVoiceForTextByDuration(text)
                local isCurrentlyPlaying = false
                if sequenceSource then
                    local ok, playing = pcall(function() return sequenceSource:isPlaying() end)
                    isCurrentlyPlaying = ok and playing
                end
                if isCurrentlyPlaying then
                    return false
                end
                local sequence = findVoiceSequenceForText(text)
                if not sequence then return false end
                writeDebugLog("tryPlayVoiceForTextByDuration: playing sequence of " .. #sequence .. " key(s) for text=" .. text:sub(1, 80) .. " -> " .. table.concat(sequence, ", "))
                local ok, err = pcall(playVoiceSequence, sequence)
                if not ok then
                    writeDebugLog("tryPlayVoiceForTextByDuration: playVoiceSequence threw: " .. tostring(err))
                end
                return true
            end

            -- TextBox.new(game, text, ...) is the one constructor every
            -- NON-BATTLE text display in the game funnels through
            -- regardless of what triggered it - catches the Oak/Pallet
            -- Town tall-grass scene (a vanilla, built-in mapScripts.
            -- onStep hook entirely separate from any hook this mod
            -- registers) and any other similar vanilla-triggered case,
            -- in one place, instead of chasing each one individually.
            -- Safe to coexist with the explicit triggers already in
            -- place: playVoiceForKey's own replay guard means a key
            -- already playing just gets left alone, not restarted, so
            -- this can't double-trigger anything.
            --
            -- Multi-line sequences (a concatenated message spanning
            -- multiple  pages) are synced to the player's own pace,
            -- not clip duration: confirmed via user report that playing
            -- the whole sequence back-to-back by duration meant the
            -- SECOND line's audio started while the player was still
            -- reading (or hadn't even pressed A past) the FIRST page.
            -- Confirmed directly from real engine source
            -- (src/render/TextBox.lua): self.pageIndex only increments
            -- inside TextBox:update when the player actually presses A/
            -- B while self.waiting is true - so the returned TextBox
            -- instance's own pageIndex is watched here, per-instance
            -- (not the shared TextBox.update, since only one box at a
            -- time ever needs this), and the next clip in the sequence
            -- only plays once the real page it belongs to is reached.
            local TextBox = mod.ui.TextBox
            if TextBox and type(TextBox.new) == "function" then
                local originalTextBoxNew = TextBox.new
                TextBox.new = function(game, text, ...)
                    local instance = originalTextBoxNew(game, text, ...)
                    local sequence = findVoiceSequenceForText(text)
                    if sequence and #sequence > 0 then
                        local ok, err = pcall(playVoiceForKey, sequence[1])
                        if not ok then
                            writeDebugLog("TextBox.new page-synced: playVoiceForKey threw for " .. tostring(sequence[1]) .. ": " .. tostring(err))
                        end
                        if #sequence > 1 and instance and type(instance) == "table" then
                            local nextIndex = 2
                            local lastPageIndex = instance.pageIndex
                            local originalInstanceUpdate = instance.update
                            if type(originalInstanceUpdate) == "function" then
                                instance.update = function(self, dt)
                                    if nextIndex <= #sequence and self.pageIndex ~= lastPageIndex then
                                        lastPageIndex = self.pageIndex
                                        local key = sequence[nextIndex]
                                        nextIndex = nextIndex + 1
                                        local playOk, playErr = pcall(playVoiceForKey, key)
                                        if not playOk then
                                            writeDebugLog("TextBox page-synced advance: playVoiceForKey threw for " .. tostring(key) .. ": " .. tostring(playErr))
                                        end
                                    end
                                    return originalInstanceUpdate(self, dt)
                                end
                            end
                        end
                    end
                    return instance
                end
            end

            -- Battle messages NEVER go through TextBox.new at all -
            -- confirmed directly from real engine source
            -- (src/battle/BattleState.lua): BattleState:say/:sayAuto
            -- just queue { text = text } onto self.queue, and
            -- BattleState:startMessage(item) - the function that
            -- actually starts displaying a queued message - builds its
            -- own custom character-by-character typing/rendering
            -- system directly (Font.encode, self.lines, self.shown),
            -- entirely separate from TextBox. This is why the mod's
            -- earlier universal TextBox.new fallback never caught any
            -- battle text ("%s wants to fight!" etc.) even though
            -- voice lines existed for it - the constructor it hooks
            -- was simply never being called for these messages.
            local okBS, BattleState = pcall(require, "src.battle.BattleState")
            if okBS and BattleState and type(BattleState.startMessage) == "function" then
                local originalStartMessage = BattleState.startMessage
                BattleState.startMessage = function(self, item)
                    if item and battleVoiceEnabled then
                        tryPlayVoiceForTextByDuration(item.text)
                    end
                    return originalStartMessage(self, item)
                end
            end

            -- Pokedex entry descriptions ALSO never go through TextBox.new
            -- or BattleState - confirmed directly from real engine source
            -- (src/ui/DexEntryMenu.lua): DexEntryMenu.render draws the
            -- description with plain Font.draw calls, one line at a time,
            -- entirely separate from both existing hooks. Voiced as Oak
            -- specifically (reclassified in dialogue_danish_voiced.csv,
            -- not a code change) since he's the one who explains Pokemon
            -- to the player throughout the game - a neutral narrator
            -- voice reading dex entries felt like the wrong character.
            --
            -- render() redraws every frame the entry screen is open (it's
            -- the :draw() body, not a one-time construction), so this
            -- relies entirely on playVoiceForKey's own replay guard to
            -- avoid restarting the clip 60 times a second - deliberately
            -- NOT tracked with any extra state here. Ownership-gating
            -- (owned = forceOwned or game.save.pokedex.owned[def.id])
            -- mirrors the real render() logic exactly, since an unseen
            -- Pokemon's entry is never actually shown either.
            local okDex, DexEntryMenu = pcall(require, "src.ui.DexEntryMenu")
            if okDex and DexEntryMenu and type(DexEntryMenu.render) == "function" then
                local originalDexRender = DexEntryMenu.render
                DexEntryMenu.render = function(game, def, sprite, forceOwned, trueColor)
                    local ok, err = pcall(function()
                        local owned = forceOwned
                            or (def and def.id and game.save.pokedex and game.save.pokedex.owned
                                and game.save.pokedex.owned[def.id])
                        local e = def and def.dexEntry
                        if owned and e and e.text then
                            playVoiceForKey(e.text)
                        end
                    end)
                    if not ok then
                        writeDebugLog("DexEntryMenu.render voice hook threw: " .. tostring(err))
                    end
                    return originalDexRender(game, def, sprite, forceOwned, trueColor)
                end
            end
        end)
        if not textMatchOk then
            writeDebugLog("TextBox.new/BattleState universal fallback setup failed: " .. tostring(textMatchErr))
        end
    end

    -- Deeper diagnostic for the silent-NPC mystery: script.command
    -- logging (below) showed ZERO commands of any kind fire for some
    -- NPCs, which rules out "wrong command name" - something more
    -- fundamental is going on. These three fire at different points in
    -- the interaction lifecycle than script.command does:
    --   world.interacted - the moment the player interacts with an NPC/
    --                       sign, before any script even starts
    --   script.started / script.ended - bracket a script's execution
    -- If world.interacted fires for the silent NPC but script.started
    -- never does, that NPC's interaction isn't running a script at all
    -- through the normal path. If NEITHER fires, the interaction isn't
    -- being recognized as a normal NPC talk in the first place.
    local function describeValue(v, depth)
        depth = depth or 2  -- how many more levels of nested tables to expand
        local vType = type(v)
        if vType == "string" or vType == "number" or vType == "boolean" then
            return tostring(v)
        elseif vType == "table" then
            if depth <= 0 then
                return "<table>"
            end
            -- Recurses into nested tables (like `target.def`, likely the
            -- NPC's actual script/dialogue reference) instead of stopping
            -- at the first level, which was hiding exactly the field
            -- we're looking for behind a bare "<table>".
            local subParts = {}
            for k2, v2 in pairs(v) do
                table.insert(subParts, tostring(k2) .. "=" .. describeValue(v2, depth - 1))
            end
            return "{ " .. table.concat(subParts, ", ") .. " }"
        else
            return "<" .. vType .. ">"
        end
    end

    local function dumpEventPayload(eventName, payload)
        if type(payload) ~= "table" then
            writeDebugLog(eventName .. " fired, payload=" .. tostring(payload))
            return
        end
        local parts = {}
        for k, v in pairs(payload) do
            table.insert(parts, tostring(k) .. "=" .. describeValue(v))
        end
        writeDebugLog(eventName .. " fired, payload={ " .. table.concat(parts, ", ") .. " }")
    end

    local function textIdToFingerprint(textId)
        local t = tostring(textId)
        if t:sub(1, 5) == "TEXT_" then
            t = t:sub(6)
        end
        t = t:gsub("_", "")
        return t:upper()
    end

    local regOkWorldInteracted, regErrWorldInteracted = pcall(mod.events.on, mod.events, "world.interacted", function(ev)
        dumpEventPayload("world.interacted", ev)

        -- Static (non-scripted) NPCs never fire script.command/show_text
        -- at all - confirmed by direct in-game testing (full command
        -- logging showed zero events for one of these). Their dialogue
        -- is instead defined directly on the map object as
        -- target.def.text, a raw engine identifier like
        -- "TEXT_PALLETTOWN_FISHER". This resolves that identifier to
        -- our pret-style key via fingerprint matching and triggers
        -- voice directly from here, since the normal path never comes.
        --
        -- For NPCs that DO also run a real script afterward, this may
        -- briefly play this resolved key's line before the real
        -- show_text call (if any) corrects it - playVoiceForKey already
        -- no-ops if the same key fires again, so the only cost is a
        -- possible brief line at the very start of an interaction, not
        -- a lasting bug.
        local ok, err = pcall(function()
            if type(ev) == "table" and ev.kind == "npc" and type(ev.target) == "table" then
                local def = ev.target.def
                if type(def) == "table" and def.text then
                    local fingerprint = textIdToFingerprint(def.text)
                    local resolvedKey = TEXT_ID_TO_KEY[fingerprint]
                    if resolvedKey then
                        writeDebugLog("world.interacted resolved def.text=" .. tostring(def.text) .. " -> key=" .. resolvedKey)
                        playVoiceForKey(resolvedKey)
                    else
                        writeDebugLog("world.interacted def.text=" .. tostring(def.text) .. " fingerprint=" .. fingerprint .. " not found in TEXT_ID_TO_KEY")
                    end
                end
            end
        end)
        if not ok then
            writeDebugLog("world.interacted resolver error: " .. tostring(err))
        end
    end)
    if not regOkWorldInteracted then
        mod.log:info("world.interacted registration failed: %s", tostring(regErrWorldInteracted))
    end
    local regOkScriptStarted, regErrScriptStarted = pcall(mod.events.on, mod.events, "script.started", function(ev)
        dumpEventPayload("script.started", ev)
    end)
    if not regOkScriptStarted then
        mod.log:info("script.started registration failed: %s", tostring(regErrScriptStarted))
    end
    local regOkScriptEnded, regErrScriptEnded = pcall(mod.events.on, mod.events, "script.ended", function(ev)
        dumpEventPayload("script.ended", ev)
        stopVoice()
    end)
    if not regOkScriptEnded then
        mod.log:info("script.ended registration failed: %s", tostring(regErrScriptEnded))
    end

    local regOkScriptCommand, regErrScriptCommand = pcall(mod.hooks.wrap, mod.hooks, "script.command", function(next, ctx, name, args)
        -- Confirmed from src/script/ScriptRunner.lua's makeContext():
        -- ctx.game is set directly. Captured here (fires on every script
        -- row, so this populates almost immediately) and reused by
        -- playVoiceForKey and other trigger points that don't have their
        -- own direct path to game.data.
        if type(ctx) == "table" and ctx.game and ctx.game.data and not cachedGameData then
            cachedGameData = ctx.game.data
        end

        -- TEMPORARY, verbose: logs every script command that fires, not
        -- just show_text, since show_text confirmed NEVER fires for some
        -- NPCs at all (not a lookup failure - it's just silent). This
        -- will find out what, if anything, actually happens when you
        -- talk to one of those NPCs. Expect a lot of log lines during
        -- normal play - that's fine, this is diagnostic-only. Once we
        -- know the real command name (if there is one), this goes back
        -- to only logging show_text.
        local argsStr = "?"
        local ok, result = pcall(function()
            if type(args) == "table" then
                local argParts = {}
                for idx, a in ipairs(args) do
                    table.insert(argParts, tostring(a))
                end
                return table.concat(argParts, ", ")
            end
            return tostring(args)
        end)
        if ok then
            argsStr = result
        end
        writeDebugLog("script.command name=" .. tostring(name) .. " args=[" .. argsStr .. "]")

        if name == "show_text" then
            local key = args[1]
            local voiceTable = (currentLanguage == "english") and ENGLISH_VOICE_LINES or DANISH_VOICE_LINES
            local found = voiceTable[key] ~= nil
            writeDebugLog("show_text key=" .. tostring(key) .. " voiceLineFound=" .. tostring(found) .. " language=" .. currentLanguage)
            writeDebugLog("about to call playVoiceForKey now, type(playVoiceForKey)=" .. type(playVoiceForKey))
            local callOk, callErr = pcall(playVoiceForKey, key)
            if not callOk then
                writeDebugLog("playVoiceForKey(key) call itself threw: " .. tostring(callErr))
            end
            writeDebugLog("returned from playVoiceForKey call, callOk=" .. tostring(callOk))
        end
        return next(ctx, name, args)
    end)

    -- Oak's introduction sequence (the very first "Hello! Welcome to the
    -- world of Pokemon!" scene) does NOT go through script.command /
    -- show_text like normal NPC dialogue - the engine handles it as its
    -- own dedicated event sequence (intro.oak_speech.build / .answered /
    -- .finished), confirmed to exist by name from the engine's own
    -- example mods, but their exact payload shape isn't documented
    -- anywhere I could find. That's why Oak's first interaction has no
    -- voice: this mod never sees it happen at all.
    --
    -- CONFIRMED from the actual engine source (src/ui/OakSpeech.lua) via
    -- a game archive the user provided - not a guess:
    --   - intro.oak_speech.build is a HOOK (Runtime.call), not an event -
    --     it rewrites the step list itself, called once up front.
    --   - intro.oak_speech.started/step/answered/finished are EVENTS
    --     (Runtime.emit). .step fires once per line of the speech with
    --     step.textKey available - and this whole sequence pushes its
    --     text boxes directly (TextBox.new), never going through
    --     script.command at all, which is exactly why it never showed up
    --     in the earlier full script.command logging.
    local function dumpPayload(eventName, payload)
        if type(payload) ~= "table" then
            mod.log:info("%s fired, payload = %s", eventName, tostring(payload))
            return
        end
        local parts = {}
        for k, v in pairs(payload) do
            table.insert(parts, tostring(k) .. "=" .. tostring(v))
        end
        mod.log:info("%s fired, payload = { %s }", eventName, table.concat(parts, ", "))
    end

    local regOkOakBuild, regErrOakBuild = pcall(mod.hooks.wrap, mod.hooks, "intro.oak_speech.build", function(next, steps, speech)
        dumpPayload("intro.oak_speech.build", { steps = steps, speech = speech })
        return next(steps, speech)  -- observe only, don't rewrite the step list
    end)
    if not regOkOakBuild then
        mod.log:info("intro.oak_speech.build registration failed: %s", tostring(regErrOakBuild))
    end
    local regOkOakStarted, regErrOakStarted = pcall(mod.events.on, mod.events, "intro.oak_speech.started", function(ev)
        dumpPayload("intro.oak_speech.started", ev)
    end)
    if not regOkOakStarted then
        mod.log:info("intro.oak_speech.started registration failed: %s", tostring(regErrOakStarted))
    end
    local regOkOakStep, regErrOakStep = pcall(mod.events.on, mod.events, "intro.oak_speech.step", function(ev)
        dumpPayload("intro.oak_speech.step", ev)
        local ok, err = pcall(function()
            -- Oak's intro runs very early - likely before any
            -- script.command has fired yet - so this is also a capture
            -- point for cachedGameData, not just a playback trigger.
            if type(ev) == "table" and type(ev.speech) == "table" and ev.speech.game and ev.speech.game.data and not cachedGameData then
                cachedGameData = ev.speech.game.data
            end
            if type(ev) == "table" and type(ev.step) == "table" and ev.step.textKey then
                writeDebugLog("intro.oak_speech.step key=" .. tostring(ev.step.textKey))
                playVoiceForKey(ev.step.textKey)
            end
        end)
        if not ok then
            writeDebugLog("intro.oak_speech.step handler error: " .. tostring(err))
        end
    end)
    if not regOkOakStep then
        mod.log:info("intro.oak_speech.step registration failed: %s", tostring(regErrOakStep))
    end
    local regOkOakAnswered, regErrOakAnswered = pcall(mod.events.on, mod.events, "intro.oak_speech.answered", function(ev)
        dumpPayload("intro.oak_speech.answered", ev)
    end)
    if not regOkOakAnswered then
        mod.log:info("intro.oak_speech.answered registration failed: %s", tostring(regErrOakAnswered))
    end
    local regOkOakFinished, regErrOakFinished = pcall(mod.events.on, mod.events, "intro.oak_speech.finished", function(ev)
        dumpPayload("intro.oak_speech.finished", ev)
        stopVoice()
    end)
    if not regOkOakFinished then
        mod.log:info("intro.oak_speech.finished registration failed: %s", tostring(regErrOakFinished))
    end

    -- Adds rows to the vanilla Options menu for on/off and volume,
    -- persisting both. The exact row shape the Options screen expects
    -- for a toggle/cycling row specifically (as opposed to a plain
    -- selectable item like the ui.start_menu.items example uses)
    -- isn't confirmed from the docs - this uses the same (label,
    -- onSelect) shape shown for other ui.* hooks, with the current
    -- state baked into the label text and onSelect cycling through
    -- values (same pattern as the on/off toggle). If these don't
    -- render like the game's other adjustable rows, check
    -- src/ui/OptionsMenu.lua for the schema it actually expects (a
    -- `value`/`type`/left-right-adjust field, etc.).
    --
    -- If a row visibly reacts (a sound plays, etc) but the ON-SCREEN
    -- LABEL TEXT doesn't update after selecting it: the underlying
    -- value is still changing correctly (mod.save:get will reflect it,
    -- and voice volume/on-off DOES apply even if the label looks
    -- stale) - the label may just not be live-refreshed by this
    -- engine's Options screen after a selection. Try leaving the
    -- Options screen and re-entering it; if the label is correct THEN,
    -- that confirms it's a display-refresh timing issue, not a broken
    -- setting.
    -- Adds rows to the vanilla Options menu for on/off and volume,
    -- persisting both. The exact row shape the Options screen expects
    -- for a toggle/cycling row specifically (as opposed to a plain
    -- selectable item like the ui.start_menu.items example uses)
    -- isn't confirmed from the docs - this uses the same (label,
    -- onSelect) shape shown for other ui.* hooks, with the current
    -- state baked into the label text and onSelect cycling through
    -- values (same pattern as the on/off toggle). If these don't
    -- render like the game's other adjustable rows, check
    -- src/ui/OptionsMenu.lua for the schema it actually expects (a
    -- `value`/`type`/left-right-adjust field, etc.).
    --
    -- HEDGE: classic Pokemon-style options screens often adjust a value
    -- with LEFT/RIGHT while a row is highlighted, rather than "select"
    -- (confirm button) cycling it - if onSelect turns out not to be
    -- what this engine calls, that would explain rows that render but
    -- don't respond. So each row below wires up onSelect AND onLeft/
    -- onRight/onChange to the same logic - harmless if unused, but
    -- covers whichever one the real engine actually calls without
    -- needing to guess a third time blind.
    --
    -- If NONE of these fire (row renders, truly nothing happens no
    -- matter what you press, even after leaving/re-entering Options),
    -- the row shape itself is wrong at a more basic level - check
    -- src/ui/OptionsMenu.lua for what a row needs to even be
    -- interactive at all.
    local regOkOptionsRows, regErrOptionsRows = pcall(mod.hooks.wrap, mod.hooks, "ui.options.rows", function(next, game, rows)
        rows = next(game, rows)

        -- ONE-TIME diagnostic: dumps the field names of the game's own
        -- EXISTING options rows (Sound, Text Speed, Game Speed, etc) to
        -- the debug log. Two rounds of guessing the interactive row
        -- schema (onSelect, then onSelect+onLeft+onRight+onChange)
        -- haven't worked - rather than guess a third time, this reads
        -- the real, working vanilla rows directly to find out what
        -- field names actually make a row respond to input.
        if not optionsRowsDumped then
            optionsRowsDumped = true
            writeDebugLog("=== vanilla options rows structure dump ===")
            for i, row in ipairs(rows) do
                local parts = {}
                for k, v in pairs(row) do
                    local vType = type(v)
                    if vType == "string" or vType == "number" or vType == "boolean" then
                        table.insert(parts, tostring(k) .. "=" .. tostring(v) .. " (" .. vType .. ")")
                    else
                        table.insert(parts, tostring(k) .. "=<" .. vType .. ">")
                    end
                end
                writeDebugLog("row " .. i .. ": { " .. table.concat(parts, ", ") .. " }")
            end
            writeDebugLog("=== end dump ===")
        end

        -- Row shape confirmed empirically from a real vanilla row dump
        -- (see the diagnostic above) - NOT a guess anymore. Real fields:
        --   label = static row title (string, doesn't change)
        --   id    = unique string identifier
        --   value = function() -> string currently displayed
        --   step  = function(direction) -> changes the value (called on
        --           left/right presumably; direction sign unconfirmed,
        --           so step() below handles both a signed direction
        --           argument and being called with no argument at all)
        -- This replaces the three earlier guesses (onSelect alone, then
        -- onSelect+onLeft+onRight+onChange) that didn't work.
        table.insert(rows, {
            label = "LANGUAGE",
            id = "danishVoiceLanguage",
            value = function()
                return currentLanguage == "english" and "ENGLISH" or "DANSK"
            end,
            step = function(direction)
                currentLanguage = (currentLanguage == "english") and "danish" or "english"
                mod.save:set("language", currentLanguage)
                stopVoice()
                mod.log:info("Language set to %s - restart for text to update (voice is already live)", currentLanguage)
            end,
        })

        table.insert(rows, {
            label = "DANISH VOICE",
            id = "danishVoiceEnabled",
            value = function()
                return voiceEnabled and "ON" or "OFF"
            end,
            step = function(direction)
                voiceEnabled = not voiceEnabled
                mod.save:set("voice_enabled", voiceEnabled)
                if not voiceEnabled then
                    stopVoice()
                end
            end,
        })

        table.insert(rows, {
            label = "VOICE VOL",
            id = "danishVoiceVolume",
            value = function()
                return voiceVolumeLevel .. "/5"
            end,
            step = function(direction)
                -- This is the only row whose step() actually inspects
                -- `direction` (the other three just flip state regardless
                -- of it). If direction isn't a plain number - a string
                -- like "left"/"right", a table, anything - `direction < 0`
                -- throws a Lua type error, which would explain a crash
                -- specifically on this row and not the other three.
                -- type(direction) == "number" guards against that for
                -- any direction type at all, not just the one guessed.
                local ok, err = pcall(function()
                    local isDecrement = (type(direction) == "number" and direction < 0)
                    if isDecrement then
                        voiceVolumeLevel = voiceVolumeLevel - 1
                        if voiceVolumeLevel < 1 then
                            voiceVolumeLevel = 5
                        end
                    else
                        voiceVolumeLevel = voiceVolumeLevel + 1
                        if voiceVolumeLevel > 5 then
                            voiceVolumeLevel = 1
                        end
                    end
                    mod.save:set("voice_volume_level", voiceVolumeLevel)
                    applyVolume()
                end)
                if not ok then
                    writeDebugLog("VOICE VOL step() error: " .. tostring(err) .. " (direction type was " .. type(direction) .. ")")
                end
            end,
        })

        table.insert(rows, {
            label = "FAST VOICE",
            id = "danishFastVoice",
            value = function()
                return fastVoiceEnabled and "ON" or "OFF"
            end,
            step = function(direction)
                fastVoiceEnabled = not fastVoiceEnabled
                mod.save:set("fast_voice_enabled", fastVoiceEnabled)
                applyPlaybackSpeed()
                mod.log:info("Fast voice set to %s - restart to (de)activate speed-change detection", tostring(fastVoiceEnabled))
            end,
        })

        table.insert(rows, {
            label = "BATTLE VOICE",
            id = "danishBattleVoiceEnabled",
            value = function()
                return battleVoiceEnabled and "ON" or "OFF"
            end,
            step = function(direction)
                battleVoiceEnabled = not battleVoiceEnabled
                mod.save:set("battle_voice_enabled", battleVoiceEnabled)
                if not battleVoiceEnabled then
                    stopVoice()
                end
            end,
        })

        return rows
    end)
    if not regOkOptionsRows then
        mod.log:info("ui.options.rows registration failed: %s", tostring(regErrOptionsRows))
    end

    mod.log:info("Danish voice lines mod loaded: %d voice lines available", 20)
end
